# Generated by Django 2.2.1 on 2019-06-04 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20190528_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
    ]
