# Generated by Django 2.2.1 on 2019-05-22 07:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('leave', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='daily_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=500)),
                ('attendance_date', models.DateField(default=datetime.date.today, verbose_name='date published')),
                ('entry_time', models.TimeField(default=django.utils.timezone.now, verbose_name='entered time :')),
                ('exit_time', models.TimeField(verbose_name='exit time:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
