# Generated by Django 2.2.1 on 2019-05-22 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20190522_1349'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_attendance',
            name='user',
        ),
        migrations.AddField(
            model_name='daily_attendance',
            name='emp_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='emp_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
            preserve_default=False,
        ),
    ]
